# Importing all the required data and libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import ast

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

### Description of all the features or columns of the table
budget = Total Amount required to make the movie

genres = Type of genre i.e action, sci fi, love story comedy etc

homepage = Official site of the movie

id = ID of the movie

Keywords = Few words that is use in the movie

original_language = original language used in the movie

original_title = original title used in the movie

overview = summary of the movie

popularity = measurement of the popular of the movie

production_companies = companies that produce the movie

production_countries = countries where the movies were shoot or that produce the movie

release_date = Release Date of the movie

Revenue = Total Amount Earned by the movie

Runtime = Total time of the movie

Spoken_languages = Languages used by the movie

Status = denotes whether movies is released or not

Tagline = Theme of the movie

Title = Title of the movie

vote_average = Average vote of the movie

vote_count = Total vote for the movie

cast = All the actors and actress working in that movie.

crew = All the staff working in that film.

In [5]:
movies.shape

(4803, 20)

In [6]:
credits.shape

(4803, 4)

In [7]:
df = movies.merge(credits, on = 'title')

In [8]:
df.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [9]:
df['crew']

0       [{"credit_id": "52fe48009251416c750aca23", "de...
1       [{"credit_id": "52fe4232c3a36847f800b579", "de...
2       [{"credit_id": "54805967c3a36829b5002c41", "de...
3       [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4       [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
                              ...
4804    [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4805    [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4806    [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4807    [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4808    [{"credit_id": "58ce021b9251415a390165d9", "de...
Name: crew, Length: 4809, dtype: object

In [10]:
df.shape

(4809, 23)

In [11]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

## Drop all the unnecessary columns

In [12]:
df.drop(['budget','homepage','original_language','original_title','production_companies','production_countries','runtime','spoken_languages','status','tagline','id','popularity','revenue','vote_average','vote_count'],axis = 1,inplace = True)

In [13]:
df.columns

Index(['genres', 'keywords', 'overview', 'release_date', 'title', 'movie_id',
       'cast', 'crew'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   genres        4809 non-null   object
 1   keywords      4809 non-null   object
 2   overview      4806 non-null   object
 3   release_date  4808 non-null   object
 4   title         4809 non-null   object
 5   movie_id      4809 non-null   int64
 6   cast          4809 non-null   object
 7   crew          4809 non-null   object
dtypes: int64(1), object(7)
memory usage: 338.1+ KB

In [15]:
df.columns

Index(['genres', 'keywords', 'overview', 'release_date', 'title', 'movie_id',
       'cast', 'crew'],
      dtype='object')

In [16]:
df = df[['movie_id','title','overview','genres','keywords','release_date','cast','crew']]

In [17]:
df

,movie_id,title,overview,genres,keywords,release_date,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",2009-12-10,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",2007-05-19,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",2015-10-26,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",2012-07-16,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",2012-03-07,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",1992-09-04,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],2011-12-26,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",2013-10-13,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],2012-05-03,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",2005-08-05,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [18]:
###### To check null value
df.isnull().sum()

movie_id        0
title           0
overview        3
genres          0
keywords        0
release_date    1
cast            0
crew            0
dtype: int64

In [19]:
df.dropna(inplace = True)

In [20]:
df.isnull().sum()

movie_id        0
title           0
overview        0
genres          0
keywords        0
release_date    0
cast            0
crew            0
dtype: int64

In [21]:
### To check duplicate data
df.duplicated().sum()

0

##### Converting genres columns into right format

In [22]:
def change(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [23]:
df['genres']= df['genres'].apply(change)

In [24]:
df

,movie_id,title,overview,genres,keywords,release_date,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",2009-12-10,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",2007-05-19,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",2015-10-26,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",2012-07-16,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",2012-03-07,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[{""id"": 5616, ""name"": ""united states\u2013mexi...",1992-09-04,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],2011-12-26,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",2013-10-13,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],2012-05-03,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",2005-08-05,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [25]:
df['keywords'] = df['keywords'].apply(change)

In [26]:
def convert(obj):
    l = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            l.append(i['name'])
            counter += 1
        else:
            break
    return l

In [27]:
df['cast'] = df['cast'].apply(convert)

In [28]:
df

,movie_id,title,overview,genres,keywords,release_date,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",2009-12-10,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",2007-05-19,"[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",2015-10-26,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",2012-07-16,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",2012-03-07,"[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...",1992-09-04,"[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],2011-12-26,"[Edward Burns, Kerry Bishé, Marsha Dietlein]","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...",2013-10-13,"[Eric Mabius, Kristin Booth, Crystal Lowe]","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],2012-05-03,"[Daniel Henney, Eliza Coupe, Bill Paxton]","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]",2005-08-05,"[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [29]:
def director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [30]:
df['crew'] = df['crew'].apply(director)

In [31]:
df['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [32]:
df['overview'] = df['overview'].apply(lambda x:x.split())

In [33]:
df

,movie_id,title,overview,genres,keywords,release_date,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",2009-12-10,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",2007-05-19,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",2015-10-26,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",2012-07-16,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",2012-03-07,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...",1992-09-04,"[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez]
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],2011-12-26,"[Edward Burns, Kerry Bishé, Marsha Dietlein]",[Edward Burns]
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...",2013-10-13,"[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith]
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],2012-05-03,"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia]
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dream girl]",2005-08-05,"[Drew Barrymore, Brian Herzlinger, Corey Feldman]",[Brian Herzlinger]


#### Remove space between two words because each word may be similar so model may confused during recommendation so by combining the two words, each word will be unique.

In [34]:
df['genres'] = df['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [35]:
df['keywords'] = df['keywords'].apply(lambda x: [i.replace(" ",'') for i in x])
df['cast'] = df['cast'].apply(lambda x: [i.replace(" ","") for i in x])
df['crew'] = df['crew'].apply(lambda x: [i.replace(" ","") for i in x])

In [36]:
df['tags'] = df['overview'] + df['genres'] + df['keywords'] + df['cast'] + df['crew']

In [37]:
df.drop(['overview','genres','keywords','cast','crew'],axis = 1,  inplace = True)

In [38]:
df

,movie_id,title,release_date,tags
0,19995,Avatar,2009-12-10,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,2007-05-19,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,2015-10-26,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,2012-07-16,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,2012-03-07,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...,...
4804,9367,El Mariachi,1992-09-04,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,2011-12-26,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered",2013-10-13,"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,2012-05-03,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,2005-08-05,"[Ever, since, the, second, grade, when, he, fi..."

In [39]:
#### convert data of tags into string from list
df['tags'] = df['tags'].apply(lambda x: " ".join(x))

In [40]:
df

,movie_id,title,release_date,tags
0,19995,Avatar,2009-12-10,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,2007-05-19,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,2015-10-26,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,2012-07-16,Following the death of District Attorney Harve...
4,49529,John Carter,2012-03-07,"John Carter is a war-weary, former military ca..."
...,...,...,...,...
4804,9367,El Mariachi,1992-09-04,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,2011-12-26,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered",2013-10-13,"""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,2012-05-03,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,2005-08-05,Ever since the second grade when he first saw ...

In [41]:
df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [42]:
df['tags'] = df['tags'].apply(lambda x:x.lower())

In [43]:
df

,movie_id,title,release_date,tags
0,19995,Avatar,2009-12-10,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,2007-05-19,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,2015-10-26,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,2012-07-16,following the death of district attorney harve...
4,49529,John Carter,2012-03-07,"john carter is a war-weary, former military ca..."
...,...,...,...,...
4804,9367,El Mariachi,1992-09-04,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,2011-12-26,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered",2013-10-13,"""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,2012-05-03,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,2005-08-05,ever since the second grade when he first saw ...

In [44]:
df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

#### Text Vectorization

In [45]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [46]:
vectors = cv.fit_transform(df['tags']).toarray()

In [47]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1950s',
 '1960s',
 '1970s',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2009',
 '20th',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '70s',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adrienbrody',
 'adult',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredhitchcock',
 'ali',
 'alice',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allowing',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusement',
 'amusementpark',
 'amy',
 'amyadams',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'anna',
 'annafaris',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'annual',
 'answer',
 'answers',
 'ant',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'article',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashes',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'asian',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assist',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'athlete',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attempttoescape',
 'attending',
 'attends',
 'attention',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'ax',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'bag',
 'bahamas',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barbrastreisand',
 'barely',
 'bargained',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'bars',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'bell',
 'belong',
 'belongs',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'book',
 'books',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brian',
 'briandepalma',
 'bride',
 'bridge',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brooklyn',
 'brooks',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunny',
 'burglar',
 'buried',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butler',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'called',
 'calls',
 'calvin',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'cannibal',
 'capable',
 'capital',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'caretaker',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'caryelwes',
 'case',
 'cases',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinedeneuve',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'cavemen',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceo',
 'ceremony',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chauffeur',
 'cheating',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chevychase',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'childprodigy',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chowyun',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christmastree',
 'christopher',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'cigarettesmoking',
 'cillianmurphy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilization',
 'civilwar',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'cloning',
 'close',
 'closer',
 'club',
 'clubs',
 'clue',
 'clueless',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'cocky',
 'code',
 'cody',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collision',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'competitive',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'concert',
 'conclusion',
 'condition',
 'conditions',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confused',
 'congress',
 'conman',
 'connected',
 'connection',
 'connell',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'conspire',
 'constant',
 'constantly',
 'construction',
 'consumed',
 'contact',
 'contain',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corner',
 'corners',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 'corruption',
 'cost',
 'costume',
 'couldn',
 ...]

#### Use of Stemming to convert similar words into unique or same words

In [48]:
import nltk

In [49]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [50]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    
    return " ".join(y)

In [51]:
df['tags'][3]

"following the death of district attorney harvey dent, batman assumes responsibility for dent's crimes to protect the late attorney's reputation and is subsequently hunted by the gotham city police department. eight years later, batman encounters the mysterious selina kyle and the villainous bane, a new terrorist leader who overwhelms gotham's finest. the dark knight resurfaces to protect a city that has branded him an enemy. action crime drama thriller dccomics crimefighter terrorist secretidentity burglar hostagedrama timebomb gothamcity vigilante cover-up superhero villainess tragichero terrorism destruction catwoman catburglar imax flood criminalunderworld batman christianbale michaelcaine garyoldman christophernolan"

In [52]:
stem("following the death of district attorney harvey dent, batman assumes responsibility for dent's crimes to protect the late attorney's reputation and is subsequently hunted by the gotham city police department. eight years later, batman encounters the mysterious selina kyle and the villainous bane, a new terrorist leader who overwhelms gotham's finest. the dark knight resurfaces to protect a city that has branded him an enemy. action crime drama thriller dccomics crimefighter terrorist secretidentity burglar hostagedrama timebomb gothamcity vigilante cover-up superhero villainess tragichero terrorism destruction catwoman catburglar imax flood criminalunderworld batman christianbale michaelcaine garyoldman christophernolan")

"follow the death of district attorney harvey dent, batman assum respons for dent' crime to protect the late attorney' reput and is subsequ hunt by the gotham citi polic department. eight year later, batman encount the mysteri selina kyle and the villain bane, a new terrorist leader who overwhelm gotham' finest. the dark knight resurfac to protect a citi that ha brand him an enemy. action crime drama thriller dccomic crimefight terrorist secretident burglar hostagedrama timebomb gothamc vigilant cover-up superhero villai tragichero terror destruct catwoman catburglar imax flood criminalunderworld batman christianbal michaelcain garyoldman christophernolan"

In [53]:
df['tags'] = df['tags'].apply(stem)

In [54]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1950s',
 '1960s',
 '1970s',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2009',
 '20th',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '70s',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adrienbrody',
 'adult',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredhitchcock',
 'ali',
 'alice',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allowing',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusement',
 'amusementpark',
 'amy',
 'amyadams',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'anna',
 'annafaris',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'annual',
 'answer',
 'answers',
 'ant',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'article',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashes',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'asian',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assist',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'athlete',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attempttoescape',
 'attending',
 'attends',
 'attention',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'ax',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'bag',
 'bahamas',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barbrastreisand',
 'barely',
 'bargained',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'bars',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'bell',
 'belong',
 'belongs',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'book',
 'books',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brian',
 'briandepalma',
 'bride',
 'bridge',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brooklyn',
 'brooks',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunny',
 'burglar',
 'buried',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butler',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'called',
 'calls',
 'calvin',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'cannibal',
 'capable',
 'capital',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'caretaker',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'caryelwes',
 'case',
 'cases',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinedeneuve',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'cavemen',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceo',
 'ceremony',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chauffeur',
 'cheating',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chevychase',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'childprodigy',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chowyun',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christmastree',
 'christopher',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'cigarettesmoking',
 'cillianmurphy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilization',
 'civilwar',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'cloning',
 'close',
 'closer',
 'club',
 'clubs',
 'clue',
 'clueless',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'cocky',
 'code',
 'cody',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collision',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'competitive',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'concert',
 'conclusion',
 'condition',
 'conditions',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confused',
 'congress',
 'conman',
 'connected',
 'connection',
 'connell',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'conspire',
 'constant',
 'constantly',
 'construction',
 'consumed',
 'contact',
 'contain',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corner',
 'corners',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 'corruption',
 'cost',
 'costume',
 'couldn',
 ...]

#### Finding the Cosine distance to measure the similarity of each movie from others i.e. distance is inversely proportional to the similiarity

In [55]:
from sklearn.metrics.pairwise import cosine_similarity

In [56]:
similarity = cosine_similarity(vectors)

In [57]:
similarity[2]

array([0.05986843, 0.06451613, 1.        , ..., 0.02677398, 0.        ,
       0.        ])

In [58]:
similarity[1].shape

(4805,)

In [59]:
similarity.shape

(4805, 4805)

In [60]:
similarity

array([[1.        , 0.08980265, 0.05986843, ..., 0.0248452 , 0.02777778,
        0.        ],
       [0.08980265, 1.        , 0.06451613, ..., 0.02677398, 0.        ,
        0.        ],
       [0.05986843, 0.06451613, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.0248452 , 0.02677398, 0.02677398, ..., 1.        , 0.0745356 ,
        0.04774099],
       [0.02777778, 0.        , 0.        , ..., 0.0745356 , 1.        ,
        0.05337605],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05337605,
        1.        ]])

In [61]:
##### To keep index position of the value same after or before sorting we use enumerate function
##### Sorting the movies similarity distances

sorted(list(enumerate(similarity[0])), reverse = True, key = lambda x:x[1])

[(0, 1.0000000000000002),
 (539, 0.25724787771376323),
 (1194, 0.2545875386086578),
 (507, 0.24720661623652207),
 (1216, 0.24595492912420727),
 (260, 0.2434322477800738),
 (1444, 0.2405626121623441),
 (582, 0.24056261216234406),
 (1920, 0.24019223070763068),
 (3730, 0.23570226039551587),
 (74, 0.22360679774997894),
 (322, 0.2222222222222222),
 (3608, 0.22075539284417395),
 (83, 0.2187974872468418),
 (61, 0.2182178902359924),
 (4192, 0.2182178902359924),
 (1537, 0.2166445612065605),
 (2333, 0.21428571428571427),
 (1204, 0.2135042050734495),
 (2409, 0.2135042050734495),
 (47, 0.21339479988815996),
 (495, 0.2132007163556104),
 (972, 0.2130032168075646),
 (942, 0.20953951903123735),
 (466, 0.20851441405707477),
 (1329, 0.20851441405707477),
 (2204, 0.20309059861498083),
 (151, 0.20211302086361077),
 (973, 0.20008168266626025),
 (1201, 0.19999999999999998),
 (2786, 0.196116135138184),
 (4048, 0.19364916731037082),
 (3162, 0.1924500897298753),
 (1275, 0.19245008972987526),
 (2999, 0.19245008972987526),
 (4405, 0.19245008972987526),
 (2971, 0.19205531989934396),
 (3538, 0.19179881852291683),
 (461, 0.1911797782254681),
 (3327, 0.1911797782254681),
 (305, 0.19050019050028574),
 (931, 0.18898223650461357),
 (150, 0.18750000000000003),
 (1321, 0.18633899812498245),
 (27, 0.1849000654084097),
 (220, 0.18257418583505536),
 (300, 0.18220272220337375),
 (1071, 0.18220272220337375),
 (36, 0.1800205749557739),
 (184, 0.1800205749557739),
 (301, 0.17928429140015906),
 (4, 0.17791499872137212),
 (373, 0.17766726362967533),
 (46, 0.17407765595569785),
 (7, 0.17391639824998364),
 (1831, 0.17201561551404662),
 (67, 0.1714985851425088),
 (1344, 0.1714985851425088),
 (2496, 0.17010345435994292),
 (2731, 0.17010345435994292),
 (149, 0.16933350266692065),
 (26, 0.1690308509457033),
 (1808, 0.16666666666666669),
 (108, 0.16666666666666666),
 (208, 0.16666666666666666),
 (661, 0.16666666666666666),
 (838, 0.16537964611894462),
 (94, 0.16343011261515333),
 (2515, 0.16343011261515333),
 (1396, 0.1617875572323585),
 (4010, 0.16169041669088863),
 (1297, 0.16012815380508713),
 (1383, 0.16012815380508713),
 (4336, 0.16012815380508713),
 (168, 0.15811388300841897),
 (31, 0.15748519708717798),
 (581, 0.15748519708717798),
 (91, 0.15474611514754322),
 (3354, 0.15474611514754322),
 (311, 0.15430334996209188),
 (1965, 0.15319083833634298),
 (502, 0.15249857033260467),
 (577, 0.15214515486254612),
 (3628, 0.15214515486254612),
 (158, 0.15075567228888181),
 (1355, 0.15075567228888181),
 (1178, 0.1496710850223124),
 (172, 0.14907119849998596),
 (490, 0.14907119849998596),
 (17, 0.1481668148335556),
 (1938, 0.1474419561548971),
 (111, 0.14731391274719738),
 (2169, 0.14731391274719738),
 (422, 0.14547859349066158),
 (505, 0.14547859349066158),
 (1488, 0.14547859349066158),
 (369, 0.14506471329641488),
 (557, 0.14506471329641488),
 (41, 0.14433756729740643),
 (84, 0.14360673947588817),
 (332, 0.14291548761875733),
 (568, 0.14291548761875733),
 (2686, 0.14291548761875733),
 (56, 0.14213381090374028),
 (249, 0.14213381090374028),
 (1322, 0.1414213562373095),
 (1220, 0.14085904245475275),
 (487, 0.13900960937138318),
 (1327, 0.13900960937138318),
 (2584, 0.13900960937138318),
 (3999, 0.13900960937138318),
 (187, 0.1388888888888889),
 (413, 0.1388888888888889),
 (1945, 0.1388888888888889),
 (1673, 0.1386750490563073),
 (2133, 0.1386750490563073),
 (4348, 0.1386750490563073),
 (2873, 0.13736056394868904),
 (2620, 0.13608276348795434),
 (2970, 0.13608276348795434),
 (4490, 0.13608276348795434),
 (52, 0.13518451760896877),
 (595, 0.13518451760896877),
 (1015, 0.13518451760896877),
 (1299, 0.13518451760896877),
 (3409, 0.13518451760896877),
 (3622, 0.13518451760896877),
 (127, 0.13471506281091267),
 (342, 0.13471506281091267),
 (2480, 0.1336306209562122),
 (134, 0.13333333333333333),
 (368, 0.13333333333333333),
 (1096, 0.13333333333333333),
 (1158, 0.13333333333333333),
 (3675, 0.13176156917368248),
 (1002, 0.13130643285972254),
 (68, 0.13074409009212268),
 (1047, 0.13074409009212268),
 (2378, 0.13074409009212268),
 (3376, 0.13074409009212268),
 (740, 0.1301448015738384),
 (1575, 0.12909944487358055),
 (1715, 0.12909944487358055),
 (529, 0.12858612496840993),
 (778, 0.12858612496840993),
 (1617, 0.12858612496840993),
 (483, 0.12830005981991682),
 (1658, 0.12830005981991682),
 (420, 0.1270821419438372),
 (1741, 0.1270001270001905),
 (939, 0.1259881576697424),
 (1747, 0.1259881576697424),
 (1833, 0.1259881576697424),
 (4672, 0.1259881576697424),
 (228, 0.1256297269074015),
 (1037, 0.1256297269074015),
 (2713, 0.1256297269074015),
 (3309, 0.1256297269074015),
 (4203, 0.125),
 (95, 0.12422599874998833),
 (432, 0.12422599874998833),
 (549, 0.12422599874998831),
 (2547, 0.12422599874998831),
 (3407, 0.1242259987499883),
 (28, 0.12379689211803457),
 (275, 0.12379689211803457),
 (1274, 0.12379689211803457),
 (2868, 0.12379689211803457),
 (50, 0.1217161238900369),
 (72, 0.1217161238900369),
 (579, 0.1217161238900369),
 (1982, 0.1217161238900369),
 (2075, 0.1217161238900369),
 (1512, 0.1215541595815788),
 (123, 0.12155415958157878),
 (454, 0.12155415958157878),
 (624, 0.12126781251816647),
 (653, 0.12126781251816647),
 (3147, 0.1203858530857692),
 (238, 0.12038585308576918),
 (1277, 0.12028130608117205),
 (1479, 0.12028130608117203),
 (692, 0.11904761904761904),
 (808, 0.11785113019775793),
 (3721, 0.11785113019775793),
 (169, 0.11785113019775792),
 (3630, 0.11785113019775792),
 (166, 0.1178511301977579),
 (232, 0.1178511301977579),
 (294, 0.1178511301977579),
 (513, 0.1178511301977579),
 (859, 0.1178511301977579),
 (1616, 0.1178511301977579),
 (1574, 0.11704114719613055),
 (5, 0.11669000700233413),
 (206, 0.11669000700233413),
 (10, 0.1160517706371319),
 (687, 0.1160517706371319),
 (1031, 0.1160517706371319),
 (2583, 0.1160517706371319),
 (3008, 0.1160517706371319),
 (199, 0.11556254088025605),
 (81, 0.11547005383792512),
 (627, 0.11470786693528086),
 (2259, 0.11470786693528086),
 (2323, 0.11470786693528086),
 (4000, 0.11470786693528086),
 (4018, 0.11470786693528086),
 (87, 0.11433239009500587),
 (126, 0.11433239009500587),
 (2450, 0.11433239009500587),
 (777, 0.11340230290662862),
 (14, 0.1126872339638022),
 (508, 0.1126872339638022),
 (854, 0.1126872339638022),
 (900, 0.1126872339638022),
 (1195, 0.1126872339638022),
 (2013, 0.1126872339638022),
 (3498, 0.1126872339638022),
 (1019, 0.11236664374387369),
 (141, 0.11180339887498947),
 (1524, 0.11180339887498947),
 (1721, 0.11180339887498947),
 (1727, 0.11180339887498947),
 (2634, 0.11180339887498947),
 (3663, 0.11180339887498947),
 (4135, 0.11180339887498947),
 (18, 0.11135885079684349),
 (2106, 0.11135885079684349),
 (2439, 0.11135885079684349),
 (312, 0.1111111111111111),
 (1082, 0.1111111111111111),
 (1294, 0.1111111111111111),
 (3340, 0.1111111111111111),
 (3620, 0.1111111111111111),
 (4097, 0.1111111111111111),
 (102, 0.11037769642208699),
 (1497, 0.11037769642208699),
 (2760, 0.11037769642208699),
 (131, 0.10959932487023819),
 (174, 0.10959932487023819),
 (266, 0.10959932487023819),
 (2072, 0.10959932487023819),
 (4079, 0.10959932487023819),
 (239, 0.10942202738310211),
 (403, 0.10942202738310211),
 (3781, 0.1091089451179962),
 (325, 0.10910894511799618),
 (773, 0.10910894511799618),
 (1156, 0.10910894511799618),
 (1373, 0.10910894511799618),
 (3055, 0.10910894511799618),
 (3954, 0.10910894511799618),
 (295, 0.10814761408717502),
 (330, 0.10814761408717502),
 (535, 0.10814761408717502),
 (754, 0.10814761408717502),
 (1273, 0.10814761408717502),
 (2181, 0.10814761408717502),
 (3102, 0.10814761408717502),
 (4230, 0.10814761408717502),
 (988, 0.10675210253672475),
 (139, 0.10669739994407998),
 (4545, 0.10669739994407998),
 (105, 0.10660035817780521),
 (233, 0.10660035817780521),
 (476, 0.10660035817780521),
 (2456, 0.10660035817780521),
 (2521, 0.10660035817780521),
 (2562, 0.10660035817780521),
 (2762, 0.10660035817780521),
 (3839, 0.10660035817780521),
 (4198, 0.10660035817780521),
 (182, 0.10540925533894598),
 (334, 0.10540925533894598),
 (643, 0.10540925533894598),
 (898, 0.10540925533894598),
 (1056, 0.10540925533894598),
 (1109, 0.10540925533894598),
 (3783, 0.10540925533894598),
 (85, 0.10482848367219183),
 (148, 0.10425720702853739),
 (263, 0.10425720702853739),
 (715, 0.10425720702853739),
 (935, 0.10425720702853739),
 (1280, 0.10425720702853739),
 (1301, 0.10425720702853739),
 (2660, 0.10425720702853739),
 (4331, 0.10425720702853739),
 (4622, 0.10425720702853739),
 (510, 0.10411584125907071),
 (3443, 0.10411584125907071),
 (307, 0.10314212462587934),
 (129, 0.10286889997472794),
 (279, 0.10286889997472794),
 (1086, 0.10286889997472794),
 (1233, 0.10286889997472794),
 (3464, 0.10286889997472794),
 (4045, 0.10286889997472794),
 (33, 0.10206207261596575),
 (35, 0.10206207261596575),
 (157, 0.10206207261596575),
 (400, 0.10206207261596575),
 (660, 0.10206207261596575),
 (781, 0.10206207261596575),
 (1501, 0.10206207261596575),
 (1942, 0.10206207261596575),
 (2661, 0.10206207261596575),
 (4256, 0.10206207261596575),
 (270, 0.10166571355506977),
 (371, 0.10166571355506977),
 (412, 0.10166571355506977),
 (870, 0.10166571355506977),
 (1202, 0.10166571355506977),
 (1439, 0.10166571355506977),
 (278, 0.10050378152592121),
 (473, 0.10050378152592121),
 (813, 0.10050378152592121),
 (933, 0.10050378152592121),
 (1276, 0.10050378152592121),
 (1823, 0.10050378152592121),
 (2003, 0.10050378152592121),
 (2284, 0.10050378152592121),
 (292, 0.1),
 (389, 0.1),
 (530, 0.1),
 (691, 0.1),
 (791, 0.1),
 (920, 0.1),
 (1077, 0.1),
 (2651, 0.1),
 (3736, 0.1),
 (410, 0.09938079899999065),
 (1089, 0.09889847151615443),
 (243, 0.09829463743659808),
 (2596, 0.09829463743659808),
 (785, 0.09820927516479827),
 (564, 0.09805806756909201),
 (1408, 0.09805806756909201),
 (1474, 0.09805806756909201),
 (1686, 0.09805806756909201),
 (2652, 0.09805806756909201),
 (3093, 0.09805806756909201),
 (589, 0.09724332766526303),
 (618, 0.09724332766526303),
 (1357, 0.09724332766526303),
 (43, 0.09622504486493763),
 (1846, 0.09622504486493763),
 (2796, 0.09622504486493763),
 (3154, 0.09622504486493763),
 (12, 0.09622504486493762),
 (23, 0.09622504486493762),
 (122, 0.09622504486493762),
 (236, 0.09622504486493762),
 (362, 0.09622504486493762),
 (1027, 0.09622504486493762),
 (1589, 0.09622504486493762),
 (1756, 0.09622504486493762),
 (2093, 0.09622504486493762),
 (2396, 0.09622504486493762),
 (596, 0.09523809523809523),
 (1418, 0.09523809523809523),
 (2488, 0.09523809523809523),
 (21, 0.0944911182523068),
 (511, 0.0944911182523068),
 (794, 0.0944911182523068),
 (922, 0.0944911182523068),
 (960, 0.0944911182523068),
 (1306, 0.0944911182523068),
 (2817, 0.0944911182523068),
 (2840, 0.0944911182523068),
 (160, 0.09435641951204964),
 (479, 0.09435641951204964),
 (1924, 0.09428090415820634),
 (1278, 0.09335200560186731),
 (1496, 0.09335200560186731),
 (1832, 0.09335200560186731),
 (112, 0.09284766908852593),
 (242, 0.09284766908852593),
 (306, 0.09284766908852593),
 (901, 0.09284766908852593),
 (1004, 0.09284766908852593),
 (1523, 0.09284766908852593),
 (3428, 0.09284766908852593),
 (4468, 0.09284766908852593),
 (799, 0.09259259259259259),
 (2274, 0.09245003270420485),
 (2388, 0.09245003270420485),
 (2856, 0.09245003270420485),
 (4353, 0.09245003270420485),
 (4502, 0.09245003270420485),
 (4516, 0.09245003270420485),
 (4653, 0.09245003270420485),
 (2448, 0.09202627172903877),
 (2968, 0.09157370929912602),
 (88, 0.09128709291752768),
 (142, 0.09128709291752768),
 (164, 0.09128709291752768),
 (227, 0.09128709291752768),
 (349, 0.09128709291752768),
 (775, 0.09128709291752768),
 (980, 0.09128709291752768),
 (1249, 0.09128709291752768),
 (1378, 0.09128709291752768),
 (1700, 0.09128709291752768),
 (1790, 0.09128709291752768),
 (3449, 0.09128709291752768),
 (3537, 0.09128709291752768),
 (4625, 0.09128709291752768),
 (170, 0.09072184232530289),
 (363, 0.09072184232530289),
 (812, 0.09072184232530289),
 (2005, 0.09072184232530289),
 (32, 0.08989331499509895),
 (107, 0.08989331499509895),
 (467, 0.08989331499509895),
 (491, 0.08989331499509895),
 (2498, 0.08989331499509895),
 (1, 0.08980265101338746),
 (75, 0.08980265101338746),
 (121, 0.08980265101338746),
 (245, 0.08980265101338746),
 (315, 0.08980265101338746),
 (356, 0.08980265101338746),
 (626, 0.08980265101338746),
 (786, 0.08980265101338746),
 (894, 0.08980265101338746),
 (937, 0.08980265101338746),
 (2167, 0.08980265101338746),
 (3301, 0.08980265101338746),
 (3816, 0.08980265101338746),
 (45, 0.0890870806374748),
 (222, 0.0890870806374748),
 (381, 0.0890870806374748),
 (2880, 0.0890870806374748),
 (4165, 0.0890870806374748),
 (4736, 0.0890870806374748),
 (2386, 0.08883363181483767),
 (96, 0.08838834764831843),
 (814, 0.08838834764831843),
 (1269, 0.08838834764831843),
 (2247, 0.08838834764831843),
 (2251, 0.08838834764831843),
 (2304, 0.08838834764831843),
 (3091, 0.08838834764831843),
 (4259, 0.08838834764831843),
 (4656, 0.08838834764831843),
 (654, 0.08830215713766959),
 (1878, 0.08830215713766959),
 (1282, 0.08753762190648169),
 (39, 0.08703882797784893),
 (86, 0.08703882797784893),
 (101, 0.08703882797784893),
 (203, 0.08703882797784893),
 (543, 0.08703882797784893),
 (547, 0.08703882797784893),
 (899, 0.08703882797784893),
 (1113, 0.08703882797784893),
 (1142, 0.08703882797784893),
 (1207, 0.08703882797784893),
 (2794, 0.08703882797784893),
 (103, 0.08679260732054925),
 (193, 0.08679260732054925),
 (501, 0.08679260732054925),
 (1828, 0.08679260732054925),
 (1139, 0.08606629658238703),
 (1405, 0.08606629658238703),
 (2250, 0.08606629658238703),
 (2339, 0.08606629658238703),
 (3069, 0.08606629658238703),
 (3218, 0.08606629658238703),
 (3441, 0.08606629658238703),
 (4492, 0.08606629658238703),
 (4717, 0.08606629658238703),
 (70, 0.08574929257125441),
 (257, 0.08574929257125441),
 (457, 0.08574929257125441),
 (634, 0.08574929257125441),
 (746, 0.08574929257125441),
 (1473, 0.08574929257125441),
 (3028, 0.08574929257125441),
 (3140, 0.08574929257125441),
 (3235, 0.08574929257125441),
 (3310, 0.08574929257125441),
 (3423, 0.08574929257125441),
 (19, 0.08535791995526398),
 (153, 0.08535791995526398),
 (1534, 0.08535791995526398),
 (1898, 0.08535791995526398),
 (51, 0.08466675133346033),
 (572, 0.08466675133346033),
 (1639, 0.08466675133346033),
 (1926, 0.08466675133346033),
 (2099, 0.08466675133346033),
 (207, 0.08451542547285165),
 (787, 0.08451542547285165),
 (1161, 0.08451542547285165),
 (2253, 0.08451542547285165),
 (2644, 0.08451542547285165),
 (63, 0.08399210511316159),
 (3431, 0.08399210511316159),
 (37, 0.08333333333333333),
 (98, 0.08333333333333333),
 (241, 0.08333333333333333),
 (472, 0.08333333333333333),
 (503, 0.08333333333333333),
 (534, 0.08333333333333333),
 (776, 0.08333333333333333),
 (885, 0.08333333333333333),
 (987, 0.08333333333333333),
 (1401, 0.08333333333333333),
 (1621, 0.08333333333333333),
 (2165, 0.08333333333333333),
 (2712, 0.08333333333333333),
 (2801, 0.08333333333333333),
 (3253, 0.08333333333333333),
 (3355, 0.08333333333333333),
 (3389, 0.08333333333333333),
 (3527, 0.08333333333333333),
 (4061, 0.08333333333333333),
 (4431, 0.08333333333333333),
 (4473, 0.08333333333333333),
 (4567, 0.08333333333333333),
 (4640, 0.08333333333333333),
 (230, 0.08268982305947231),
 (82, 0.08219949365267865),
 (223, 0.08219949365267865),
 (254, 0.08219949365267865),
 (329, 0.08219949365267865),
 (471, 0.08219949365267865),
 (632, 0.08219949365267865),
 (680, 0.08219949365267865),
 (1614, 0.08219949365267865),
 (2683, 0.08219949365267865),
 (3470, 0.08219949365267865),
 (190, 0.08206099398622181),
 (2763, 0.08206099398622181),
 (2203, 0.08144629623753681),
 (16, 0.08111071056538127),
 (71, 0.08111071056538127),
 (138, 0.08111071056538127),
 (1560, 0.08111071056538127),
 (1765, 0.08111071056538127),
 (3910, 0.08111071056538127),
 (4055, 0.08111071056538127),
 (4451, 0.08111071056538127),
 (62, 0.08084520834544431),
 (205, 0.08084520834544431),
 (256, 0.08084520834544431),
 (850, 0.08084520834544431),
 (1045, 0.08084520834544431),
 (1323, 0.08084520834544431),
 (1655, 0.08084520834544431),
 (1664, 0.08084520834544431),
 (2326, 0.08084520834544431),
 (2659, 0.08084520834544431),
 (2789, 0.08084520834544431),
 (2882, 0.08084520834544431),
 (3155, 0.08084520834544431),
 (3832, 0.08084520834544431),
 (11, 0.08006407690254357),
 (365, 0.08006407690254357),
 (1289, 0.08006407690254357),
 (1290, 0.08006407690254357),
 (1367, 0.08006407690254357),
 (2820, 0.08006407690254357),
 (3206, 0.08006407690254357),
 (3701, 0.08006407690254357),
 (274, 0.07945521577046602),
 (587, 0.07905694150420949),
 (737, 0.07905694150420949),
 (2163, 0.07905694150420949),
 (2592, 0.07905694150420949),
 (2916, 0.07905694150420949),
 (4083, 0.07905694150420949),
 (4639, 0.07905694150420949),
 (125, 0.07874259854358899),
 (59, 0.07856742013183862),
 (189, 0.07856742013183862),
 (200, 0.07856742013183862),
 (313, 0.07856742013183862),
 (800, 0.07856742013183862),
 (1288, 0.07856742013183862),
 (1521, 0.07856742013183862),
 (2317, 0.07856742013183862),
 (2410, 0.07856742013183862),
 (2551, 0.07856742013183862),
 (3398, 0.07856742013183862),
 (3430, 0.07856742013183862),
 (4412, 0.07856742013183862),
 (271, 0.07808688094430304),
 (732, 0.07808688094430304),
 (908, 0.07808688094430304),
 (1175, 0.07808688094430304),
 (2395, 0.07808688094430304),
 (2831, 0.07808688094430304),
 (55, 0.07749842582921285),
 (76, 0.07715167498104596),
 (79, 0.07715167498104596),
 (591, 0.07715167498104596),
 (665, 0.07715167498104596),
 (1325, 0.07715167498104596),
 (2363, 0.07715167498104596),
 (3022, 0.07715167498104596),
 (4123, 0.07715167498104596),
 (2354, 0.07715167498104594),
 (109, 0.07647191129018724),
 (179, 0.07647191129018724),
 (1005, 0.07647191129018724),
 (1348, 0.07647191129018724),
 (1769, 0.07647191129018724),
 (2136, 0.07647191129018724),
 (2212, 0.07647191129018724),
 (2381, 0.07647191129018724),
 (3072, 0.07647191129018724),
 (3982, 0.07647191129018724),
 (3994, 0.07647191129018724),
 (4006, 0.07647191129018724),
 (4099, 0.07647191129018724),
 (674, 0.07624928516630233),
 (784, 0.07624928516630233),
 (1623, 0.07624928516630233),
 (1632, 0.07624928516630233),
 (2021, 0.07624928516630233),
 (2052, 0.07624928516630233),
 (2241, 0.07624928516630233),
 (2701, 0.07624928516630233),
 (3188, 0.07624928516630233),
 (3907, 0.07624928516630233),
 (229, 0.07597371763975863),
 (488, 0.07548513560963971),
 (9, 0.07537783614444091),
 (419, 0.07537783614444091),
 (536, 0.07537783614444091),
 (782, 0.07537783614444091),
 (1446, 0.07537783614444091),
 (1883, 0.07537783614444091),
 (97, 0.07453559924999299),
 (212, 0.07453559924999299),
 (635, 0.07453559924999299),
 (728, 0.07453559924999299),
 (752, 0.07453559924999299),
 (827, 0.07453559924999299),
 (979, 0.07453559924999299),
 (2650, 0.07453559924999299),
 (3390, 0.07453559924999299),
 (3822, 0.07453559924999299),
 (570, 0.07453559924999298),
 (1292, 0.07453559924999298),
 (1770, 0.07453559924999298),
 (2161, 0.07453559924999298),
 (2698, 0.07453559924999298),
 (2787, 0.07453559924999298),
 (3241, 0.07453559924999298),
 (4403, 0.07453559924999298),
 (4443, 0.07453559924999298),
 (1018, 0.07372097807744857),
 (1146, 0.07372097807744857),
 (1340, 0.07372097807744857),
 (1701, 0.07372097807744857),
 (1996, 0.07372097807744857),
 (2056, 0.07372097807744857),
 (183, 0.07362101738323101),
 (215, 0.07293249574894728),
 (704, 0.07293249574894728),
 (997, 0.07293249574894728),
 (1168, 0.07293249574894728),
 (2018, 0.07293249574894728),
 (2320, 0.07293249574894728),
 (4343, 0.07293249574894728),
 (100, 0.07273929674533079),
 (267, 0.07273929674533079),
 (336, 0.07273929674533079),
 (1166, 0.07273929674533079),
 (1171, 0.07273929674533079),
 (1262, 0.07273929674533079),
 (1737, 0.07273929674533079),
 (1774, 0.07273929674533079),
 (1990, 0.07273929674533079),
 (2114, 0.07273929674533079),
 (2533, 0.07273929674533079),
 (3671, 0.07273929674533079),
 (3976, 0.07273929674533079),
 (30, 0.07216878364870322),
 (281, 0.07216878364870322),
 (2888, 0.07216878364870322),
 (3225, 0.07216878364870322),

In [62]:
##### To display top 5 sorted movies based on similarity distances
sorted(list(enumerate(similarity[0])), reverse = True, key = lambda x:x[1])[1:6]

[(539, 0.25724787771376323),
 (1194, 0.2545875386086578),
 (507, 0.24720661623652207),
 (1216, 0.24595492912420727),
 (260, 0.2434322477800738)]

In [63]:
def recommend(movie):
    movie_index = df[df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse = True, key = lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(df.iloc[i[0]].title)

In [64]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman
Batman & Robin

In [65]:
df.iloc[539].title

'Titan A.E.'

In [66]:
df.iloc[507].title

'Independence Day'

In [67]:
import pickle

In [68]:
pickle.dump(df, open('movies.pkl','wb'))

In [70]:
pickle.dump(similarity, open('similarity.pkl','wb'))

In [ ]:
pickle.dump(movies, open('movies.pkl','wb'))